"""empty message

Revision ID: 090d9565c5e5
Revises: 8671b25a703a
Create Date: 2025-04-11 22:07:46.997308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090d9565c5e5'
down_revision = '8671b25a703a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Planet', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planets', ['Planet'], ['id'])

    with op.batch_alter_table('fav_starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Starship', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'starships', ['Starship'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_starship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Starship')

    with op.batch_alter_table('fav_planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Planet')

    # ### end Alembic commands ###
