"""empty message

Revision ID: 37825f729633
Revises: b47e90c6c594
Create Date: 2025-04-11 21:43:28.957361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37825f729633'
down_revision = 'b47e90c6c594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['User'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_character')
    # ### end Alembic commands ###
