"""empty message

Revision ID: 8671b25a703a
Revises: 89e589d88709
Create Date: 2025-04-11 22:05:49.039218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8671b25a703a'
down_revision = '89e589d88709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Character', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'characters', ['Character'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Character')

    # ### end Alembic commands ###
