"""empty message

Revision ID: 89e589d88709
Revises: 37825f729633
Create Date: 2025-04-11 22:03:52.772313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e589d88709'
down_revision = '37825f729633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['User'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav_starship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['User'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_starship')
    op.drop_table('fav_planet')
    # ### end Alembic commands ###
