"""empty message

Revision ID: b47e90c6c594
Revises: d3a1e00fb4c8
Create Date: 2025-04-11 21:21:34.125724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47e90c6c594'
down_revision = 'd3a1e00fb4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=20), nullable=False),
    sa.Column('Number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=20), nullable=False),
    sa.Column('Size', sa.String(length=1000), nullable=False),
    sa.Column('Seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('Heigth', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('Heigth')
        batch_op.drop_column('Name')

    op.drop_table('starships')
    op.drop_table('planets')
    # ### end Alembic commands ###
